# Generated by Django 2.1.3 on 2018-11-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AECOnews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AECOnews.User')),
                ('asdf', models.CharField(max_length=50)),
            ],
            bases=('AECOnews.user',),
        ),
    ]
