# Generated by Django 2.1.3 on 2018-11-24 18:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('AECOnews', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='crator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='profiles.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=datetime.datetime),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
