# Generated by Django 2.1.3 on 2018-11-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AECOnews', '0003_auto_20181124_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='crator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Client'),
        ),
    ]
