# Generated by Django 2.1.3 on 2018-11-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(null=True, upload_to='post_image')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(null=True, upload_to='post_image')),
            ],
        ),
        migrations.CreateModel(
            name='Treballador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(null=True, upload_to='post_image')),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(max_length=50)),
                ('localidad', models.TextField(max_length=200)),
                ('fecha_registro', models.DateTimeField()),
            ],
        ),
    ]
