# Generated by Django 2.1.3 on 2018-11-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20181124_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesionals',
            new_name='Profesionales',
        ),
    ]
