# Generated by Django 2.1.3 on 2018-11-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20181124_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesionales',
            new_name='Profesional',
        ),
    ]
